main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 30
  - name: Research
    url: '#research'
    weight: 40
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Projects
    url: '#projects'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70