main:
  - name: Bio
    url: /
    weight: 10
  - name: Experience
    url: '/#experience'
    weight: 30
  - name: My Research
    url: '/#myresearch'
    weight: 40
  - name: Publications
    url: '/#publications'
    weight: 50
  - name: Projects
    url: '/#projects'