# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Alan L. V. Guedes'
    description: 'Alan L. V. Guedes'
    twitter: 'alanlivio'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
    
# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Alan Guedes"
    
# Site footer
footer:
  copyright:
    notice: '© {year} Alan Guedes. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true
      
# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  
# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  syntax_highlighter:
    enable: false
    extra_languages:
      - latex
      - python
  repository:
    url: 'https://github.com/alanlivio/alanlivio.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''