site_name: Alan Guedes
site_author: Alan Guedes
site_url: http://alanlivio.github.io
site_description: Alan Guedes website
copyright: MIT
remote_branch: gh-pages
repo_url: https://github.com/alanlivio/alanlivio.github.io
edit_uri: edit/master/docs/
docs_dir: "src"

nav:
  - "About me": index.md
  - "projects.md"

plugins:
  - search
  - macros:
      verbose: false

theme:
  icon:
    logo: fontawesome/solid/code
  name: material
  custom_dir: src/templates
  locale: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  nav_style: dark
  include_sidebar: false

markdown_extensions:
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: google
    property: G-P8VQHVLPZD
  social:
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/alanlivio"
    - icon: fontawesome/brands/github
      link: "https://github.com/alanlivio"
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/alanlivio"
    - icon: fontawesome/solid/flask
      link: "https://scholar.google.com/citations?user=alanlivio"
    - icon: fontawesome/solid/envelope
      link: "mailto:alan@telemidia.puc-rio.br"
  reseacher:
    name: Alan Guedes
    role: UCL, LASP Reseacher
    cv_file: cv.pdf
    github_avatar: https://avatars.githubusercontent.com/u/604808
    interests:
      - Multiemdia
      - Immersive Media
      - Adaptative Streaming
    experience:
      - role: Reasercher
        place: LASP Lab, UCL
        url: "http://www.lasp2013.com"
        location: London
        peorid: "2021-today"
        icon: fontawesome/solid/flask
      - role: Reasercher
        place: TeleMidia Lab, PUC-RIo
        url: "http://www.telemdia.puc-rio.br"
        location: Rio de Janeiro
        peorid: "2013-2021"
        icon: fontawesome/solid/flask
      - role: Reasercher
        place: Lavid Lab, UFPB
        url: "http://www.lavid.ufpb.br"
        location: João Pessoa
        peorid: "2009-2013"
        icon: fontawesome/solid/flask
    education:
      - course: PhD in Computer Science
        institution: PUC-Rio
        period: 2013-2017
        url: "http://www.puc-rio.br/"
        icon: fontawesome/solid/book-open
      - course: MSc in Computer Science
        institution: UFPB
        period: 2010-2012
        url: "http://www.ufpb.br/"
        icon: fontawesome/solid/book-open
      - course: BSc in Computer Science
        institution: UFPB
        period: 2005-2009
        url: "http://www.ufpb.br/"
        icon: fontawesome/solid/book-open
    shortbio: >
      I am Multimedia Researcher with development and interpersonal skills to work on research projects. I am currently a postdoc at UCL working on Immersive Media. I hold a PhD (2017) from PUC-Rio and an M.Sc. (2012) from UFPB, where I collaborated on TeleMidia and Lavid labs, respectively. During my career, I collaborated on video/TV/machine learning projects, research communities (SBC WebMedia and SIGMM), and standard committees (Brazilian TV Forum and ITU SG16). My research interests are Immersive Media, Interactive Multimedia, and Multimedia Analyses, where I seek to get involved in purpose-driven research with technology transfer to industry or social impact.
    shortbio_social: >
      I believe that technology can be a vehicle for social impact, especially in multimedia field. Today, multimedia/web/video data are spread and can be for accessibility, governance transparency, minority inclusion, social justice/activism, etc. This way, I annually organize a workshop to instigate Brazilian students/research in this direction. See more at https://webmedia.org.br/2021/lf-vi-premio-luiz-fernando-de-computacao (PT-BR).
    clipping:
      - https://www.rnp.br/en/rnp-and-microsoft-challenge-artificial-intelligence
      - http://www.inf.puc-rio.br/blog/noticia/noticia/pesquisadores-do-telemidia-lab-publicam-artigo-sobre-nova-versao-do-ginga
      - http://www.inf.puc-rio.br/blog/noticia/noticia/por-dentro-do-di-telemidia-trabalha-com-sistemas-multimidia-e-hipermidia
    volunteering:
      - title: International Telecommunication Union
        description: >
          - ITU-T SG-16/Q13: Contributor to H.761/Ginga-NCL specification
        link: https://www.itu.int/en/ITU-T/studygroups/2017-2020/16/Pages/default.aspx
      - title: Forum SBTVD
        description: >
          - Tecnical Module: Contributor to Ginga-NCL specification
        link: https://forumsbtvd.org.br/
      - title: SBC
        description: >
          - WebMedia (Brazilian Symposium on Multimedia and Web): Reviewer (2013-2019); Chair of Scientific
          Initiation Workshop (2018); Chair of Tools and Applications Initiation Workshop (2019); and Luiz
          Fernando Award Committee (2017-2019)
          - CBIE (Brazilian Conference on Informatics for Education): Reviewer (2019)
        link: https://webmedia.org/
    accomplishments:
      - certificate_url: "http://itu.int/en/ITU-T/challenges/pages/iptv.aspx"
        year: 2013
        organization: International Telecomunication Union - ITU
        title: "Honourable mention on IPTV Application Challenge to GingaAppStore project"
        icon: fontawesome/solid/trophy
      - certificate_url: "http://set.org.br/artigos/ed137/137_revistadaset_70.pdf"
        year: 2013
        organization: Brazilian Broadcast Asssociation - SET
        title: "Best Interactivity Solution to Brasil4D project"
        icon: fontawesome/solid/trophy
    projects:
      - title: bash-helpers
        period: "2016-today"
        logo: "http://alanlivio.github.io/bash-helpers/logo.svg"
        description: >
          Cross-platform (linux, windows, macOS) bash helpers to configure OS (dark mode, disable animations), install/update software (python, vscode, docker, wsl, msys) and useful utilities (dotfiles, git, compress, curl).
        github:
          name: alanlivio/bash-helpers
          url: "http://alanlivio.github.io/bash-helpers"
      - title: Ginga PUC-Rio Player
        period: "2013-today"
        logo: https://upload.wikimedia.org/wikipedia/commons/c/ce/Ginga_Middleware_Logo.png
        description: >
          PUC-Rio implemnatino of Ginga SBTVD/ITU standard.
        github:
          name: TeleMidia/ginga
          url: "http://github.com/telemidia/ginga"
      - title: ncl-blocks
        period: "2017"
        logo: "https://github.com/TeleMidia/nclblocks/raw/master/docs/overview1.png"
        description: >
          NCLBlocks is tool based in Google Blocks to enable a block-oriented development of NCL applications.
        github:
          name: Telemidia/ncl-blocks
          url: "http://github.com/TeleMidia/ncl-blocks"
      - title: Brasil4D
        period: "2016"
        logo: "https://agenciabrasil.ebc.com.br/sites/default/files/atoms/image/ivani_e_filha_costas.marcela_boa.png"
        url_video: "https://www.youtube.com/embed/T5hE0l_NkfY"
        description: >
          The Brasil4D was funded by the World Bank and focused on Ginga social impact.
          This project performed transmission and digital reception of interactive video applications (using Ginga technology) to 100 low-income families.
          Those applications presented education and health contents, besides labor opportunities.
          The Brazilian Broadcast Community SET awarded Brasil4D as Best interactivity solution.
          It also received awards from the La Cumbre TV Abierta and FRIDA Program because its innovative technological solutions and social impact.
          We describe this impact in a report from the World Bank.
        read_more:
          text: "Word Bank report"
          url: "http://documents.worldbank.org/curated/en/232621468230956108/pdf/809560WP0PORTU0Box0379824B00PUBLIC0.pdf"
