name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: build cv.pdf
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk -pdflua latex/cv.tex -cd -output-directory="../mkdocs"
      - name: build certificates.pdf
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk -pdflua latex/certificates -cd -output-directory="../mkdocs"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: zensical-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            zensical-
      - run: pip install -r requirements.txt
      - run: zensical build
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
