name: Deploy site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build latex
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: make -C website latex
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: make -C website deps
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build website
        run: make -C website build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/site

  deploy-website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-website
    runs-on: ubuntu-latest
    name: Deploy website
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
