name: main
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "latex/*"
      - "mkdocs/*"
      - "mkdocs.yml"

permissions:
  contents: write

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python build_tex_partials_from_mkdocs_yml.py
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk -pdf latex/cv.tex -cd -output-directory=../mkdocs
      # https://github.com/mkdocs/mkdocs/discussions/2369
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: mkdocs gh-deploy --force
